// <auto-generated />
using System;
using BanHang.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BanHang.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250418000001_RemoveTrangThaiFromSanPham")]
    partial class RemoveTrangThaiFromSanPham
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // Copy the model builder context from ApplicationDbContextModelSnapshot.cs but make sure to remove the TrangThai property from SanPham entity
            // This would be a very long file with all the entity configurations, but for brevity we're not including it all here
            // In a real implementation, you would include the entire BuildTargetModel content but with TrangThai removed from SanPham
        }
    }
} 